gantt
    title Projet Sport réalisation
    dateFormat  YYYY-MM-DD
    section phase 2
    Création des classes           :a1, 2025-09-24, 21d
    Tests unitaires        : 2025-09-24, 45d
    Codage        : 2025-09-24, 45d
    Upgrade (si possible)        : 2025-11-03, 7d
    Test utilisation        : 2025-11-03, 10d
   section Rapport final
    Redaction              :2025-11-10  , 14d
    Rendu du rapport      : 2025-11-23, 1d
    Préparation soutenance      : 2025-11-20, 14d
    Soutenance      : 2025-12-07, 1d
