gantt
    title Projet Sport Etape préliminaire
    dateFormat  YYYY-MM-DD
    section phase 1
    Cahier des charges           :a1, 2025-09-04, 5d
    Mise en place de GIT        : 2025-09-11, 2d
    Diagramme des classes        : 2025-09-04, 12d
    Diagramme des cas d'utilisation        : 2025-09-11, 2d
    section Rapport
    Redaction               :2025-09-12  , 14d
    Rendu du rapport      : 2025-09-26, 1d
