# =========================================================
# signatures_dao.py
# -----------------
# Ce fichier définit les signatures des DAO du projet.
# Il n'est pas implémenté, il sert uniquement de référence.
# =========================================================


from typing import List, Optional
from business_object.utilisateur import Utilisateur
from business_object.activite import Activite
from business_object.commentaire import Commentaire
from business_object.jaime import Jaime
from business_object.abonnement import Abonnement


# =========================================================
# UtilisateurDao
# =========================================================
class UtilisateurDao:
    def creer(self, utilisateur: Utilisateur) -> int: ...
    def trouver_par_id(self, id_utilisateur: int) -> Optional[Utilisateur]: ...
    def lister_tous(self) -> List[Utilisateur]: ...
    def modifier(self, utilisateur: Utilisateur) -> bool: ...
    def supprimer(self, id_utilisateur: int) -> bool: ...
    def se_connecter(self, pseudo, mdp) -> Optional[Utilisateur]: ...


# =========================================================
# ActiviteDao
# =========================================================
class ActiviteDao:
    def creer(self, activite: Activite) -> int: ...
    def trouver_par_id(self, id_activite: int) -> Optional[Activite]: ...
    def lister_par_utilisateur(self, id_utilisateur: int) -> List[Activite]: ...
    def modifier(self, activite: Activite) -> bool: ...
    def supprimer(self, id_activite: int) -> bool: ...


# =========================================================
# CommentaireDao
# =========================================================
class CommentaireDao:
    def creer(self, commentaire: Commentaire) -> int: ...
    def lister_par_activite(self, id_activite: int) -> List[Commentaire]: ...
    def supprimer(self, id_commentaire: int) -> bool: ...


# =========================================================
# JaimeDAO
# =========================================================
class JaimeDao:
    def creer(self, jaime: Jaime) -> bool: ...
    def lister_par_activite(self, id_activite: int) -> List[Jaime]: ...
    def existe(self, id_activite: int, id_auteur: int) -> bool: ...
    def supprimer(self, id_jaime: int) -> bool: ...


# =========================================================
# AbonnementDao
# =========================================================
class AbonnementDao:
    def creer(self, abonnement: Abonnement) -> bool: ...
    def trouver_par_id(
        self, 
        id_utilisateur_suiveur: int, 
        id_utilisateur_suivi: int
    ) -> Optional[Abonnement]:
        ...
    def lister_ids_suivis_par_utilisateur(self, id_utilisateur_suiveur: int) -> List[int]: ...
    def lister_ids_suiveurs_par_utilisateur(self, id_utilisateur_suivi: int) -> List[int]: ...
    def supprimer(self, id_abonnement: int) -> bool: ...
