# =========================================================
# signatures_dao.py
# -----------------
# Ce fichier définit les signatures des DAO du projet.
# Il n'est pas implémenté, il sert uniquement de référence
# pour les développeurs.
# =========================================================


from typing import List
from business_object.utilisateur import Utilisateur
from business_object.activite import Activite
from business_object.commentaire import Commentaire
from business_object.jaime import Jaime
from business_object.abonnement import Abonnement


# =========================================================
# UtilisateurDao
# =========================================================
class UtilisateurDao:
    def creer(self, utilisateur: Utilisateur, mot_de_passe: str) -> bool: ...
    def trouver_par_pseudo(self, pseudo: str) -> Utilisateur | None: ...
    def trouver_par_id(self, id_utilisateur: int) -> Utilisateur | None: ...
    def lister_tous(self) -> List[Utilisateur]: ...
    def modifier(self, utilisateur: Utilisateur) -> bool: ...
    def supprimer(self, id_utilisateur: int) -> bool: ...
    def verifier_pseudo_existant(self, pseudo: str) -> bool: ...
    def verifier_id_existant(self, id_utilisateur: int) -> bool: ...
    def se_connecter(self, pseudo: str, mot_de_passe: str) -> Utilisateur | None: ...


# =========================================================
# ActiviteDao
# =========================================================
class ActiviteDao:
    def creer(self, activite: Activite) -> Activite: ...
    def trouver_par_id(self, id_activite: int) -> Activite | None: ...
    def modifier(self, activite: Activite) -> bool: ...
    def supprimer(self, id_activite: int) -> bool: ...
    def lister_par_utilisateur(self, id_utilisateur: int) -> List[Activite]: ...
    def lister_activites_filtres(
        self,
        id_utilisateur: int,
        sport: str = None,
        date_debut: str = None,
        date_fin: str = None,
    ) -> List[Activite]: ...
    def verifier_id_existant(self, id_activite: int) -> bool: ...


# =========================================================
# CommentaireDao
# =========================================================
class CommentaireDao:
    def creer(self, commentaire: Commentaire) -> Commentaire: ...
    def lister_par_activite(self, id_activite: int) -> List[Commentaire]: ...
    def supprimer(self, id_commentaire: int) -> bool: ...
    def trouver_par_id(self, id_commentaire: int) -> Commentaire | None: ...


# =========================================================
# JaimeDAO
# =========================================================
class JaimeDao:
    def creer(self, jaime: Jaime) -> Jaime: ...
    def lister_par_activite(self, id_activite: int) -> List[Jaime]: ...
    def supprimer(self, id_activite: int, id_auteur: int) -> bool: ...
    def existe(self, id_activite: int, id_auteur: int) -> bool: ...
    def compter_par_activite(self, id_activite: int) -> int: ...


# =========================================================
# AbonnementDao
# =========================================================
class AbonnementDao:
    def creer(self, abonnement: Abonnement) -> Abonnement: ...
    def trouver_par_ids(
        self, id_utilisateur_suiveur: int, id_utilisateur_suivi: int
    ) -> Abonnement | None: ...
    def lister_suivis(self, id_utilisateur: int) -> List[Abonnement]: ...
    def lister_suiveurs(self, id_utilisateur: int) -> List[Abonnement]: ...
    def lister_tous(self) -> List[Abonnement]: ...
    def supprimer(
        self, id_utilisateur_suiveur: int, id_utilisateur_suivi: int
    ) -> bool: ...
